version: '3'
services:
  jenkins:
    image: debian:stable
    container_name: jenkins-container
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/lib/jenkins
    command: /bin/bash -c "apt-get update && apt-get install -y wget sudo && wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add - && sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list' && sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5BA31D57EF5975CA && sudo apt update && sudo apt install -y jenkins && sudo systemctl start jenkins && tail -f /dev/null"
    restart: always
volumes:
  jenkins-data:
